spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/Workspace/JPA_PlayGround/jpashop;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    data-password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true #시스템 아웃으로 출력하는데 운영시 제거해야함
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:

logging:
  level:
    org.hibernate.SQL: debug

