spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
            scope: email, profile
          google:
            clientId:
            clientSecret:
            scope: email, profile
