spring:

  datasource:
    url: jdbc:h2:mem:testdb
    # jdbc:h2:tcp:/mem/localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql:true

logging:
  level:
    org.hibernate.SQL: debug
